version: '3.8'

services:
  caddy:
    image: caddy:2.8
    restart: unless-stopped
    ports:
      - "1160:80"
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/_site:/srv
      - ./caddy_data:/data
      - ./caddy_config:/config
